using System.Globalization;
using System.Reflection.Emit;
using System.Text;
using System.Text.Json;
using Transpiler.Core;

namespace Transpiler.Backends;

public enum SourceTarget { JavaScript, Python }
public sealed record GeneratedSource(string Text, string Extension, int MethodCount, int InstructionCount);

/// <summary>
/// Emits ordinary target-language functions. Each CIL instruction becomes concrete source statements;
/// the generated control-flow dispatcher selects statically generated blocks, never interprets bytecode.
/// </summary>
public static class SourceEmitter
{
    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
    public static GeneratedSource Emit(CompilationAnalysis analysis, SourceTarget target)
    {
        var python = target == SourceTarget.Python;
        var metadata = new BackendMetadata(analysis);
        var json = JsonSerializer.Serialize(metadata.Build(), JsonOptions);
        var resource = python ? "Transpiler.Runtime.Python" : "Transpiler.Runtime.JavaScript";
        using var stream = typeof(SourceEmitter).Assembly.GetManifestResourceStream(resource)
            ?? throw new InvalidOperationException($"Missing embedded runtime: {resource}");
        using var reader = new StreamReader(stream, Encoding.UTF8);
        var output = new StringBuilder();
        output.AppendLine(python ? "# Generated by Transpiler. Profile: portable-mvp; metadata schema: 2." : "// Generated by Transpiler. Profile: portable-mvp; metadata schema: 2.");
        if (analysis.Methods.Any(m => m.Method.Instructions.Length > 0 && AssemblyLinker.IsFramework(m.Method.Reference.Assembly)))
        {
            using var notice = typeof(SourceEmitter).Assembly.GetManifestResourceStream("Transpiler.Runtime.DotNetNotice")!;
            using var noticeReader = new StreamReader(notice, Encoding.UTF8);
            foreach (var line in noticeReader.ReadToEnd().Split('\n')) output.AppendLine((python ? "# " : "// ") + line);
        }
        output.AppendLine(reader.ReadToEnd());
        using var extension = typeof(SourceEmitter).Assembly.GetManifestResourceStream(python ? "Transpiler.Runtime.Python.Managed" : "Transpiler.Runtime.JavaScript.Managed")!;
        using var extensionReader = new StreamReader(extension, Encoding.UTF8);
        output.AppendLine(extensionReader.ReadToEnd());
        using var services = typeof(SourceEmitter).Assembly.GetManifestResourceStream(python ? "Transpiler.Runtime.Python.Services" : "Transpiler.Runtime.JavaScript.Services")!;
        using var servicesReader = new StreamReader(services, Encoding.UTF8);
        output.AppendLine(servicesReader.ReadToEnd());
        if (python)
        {
            output.AppendLine("def retain(value): return R.retain(value)\ndef dereference(handle): return R.dereference_root(handle)\ndef release(handle): return R.release(handle)\ndef runtime_info(): return R.runtime_info()");
            output.AppendLine("import json as _json");
            output.AppendLine("metadata = _json.loads(" + Quote(json) + ")");
            output.AppendLine("R = HostedRuntime(metadata)");
        }
        else
        {
            output.AppendLine("export function retain(value) { return R.retain(value); }\nexport function dereference(handle) { return R.dereference_root(handle); }\nexport function release(handle) { return R.release(handle); }\nexport function runtimeInfo() { return R.runtime_info(); }");
            output.AppendLine("const metadata = " + json + ";");
            output.AppendLine("const R = new HostedRuntime(metadata);");
        }
        var count = 0;
        foreach (var method in analysis.Methods)
        {
            EmitMethod(output, method, metadata, analysis.Assembly, python);
            count += method.StackBefore.Count;
        }
        foreach (var method in analysis.Methods)
            output.AppendLine("R.functions[" + Quote(BackendMetadata.Id(method.Method.Token)) + "] = m_" + method.Method.Token + (python ? "" : ";"));
        if (python)
        {
            output.AppendLine("\ndef invoke(name, args=()):\n    return R.invoke_export(name, list(args))");
            output.AppendLine("\nasync def invoke_async(name, args=(), max_steps=100000):\n    return await R.await_export(name, list(args), max_steps)");
            output.AppendLine("\ndef main(args=()):\n    return R.main(list(args))");
            output.AppendLine("\ndef set_output(writer):\n    R.write = writer");
            output.AppendLine("\nif __name__ == '__main__' and metadata['entry'] is not None:\n    try:\n        sys.exit(main(sys.argv[1:]))\n    except CliError as error:\n        sys.stderr.write(str(error) + '\\n')\n        sys.exit(1)");
        }
        else
        {
            output.AppendLine("export function invoke(name, args = []) { return R.invoke_export(name, args); }");
            output.AppendLine("export async function invokeAsync(name, args = [], options = {}) { return await R.await_export(name, args, options); }");
            output.AppendLine("export function main(args = []) { return R.main(args); }");
            output.AppendLine("export function setOutput(writer) { if (typeof writer !== 'function') throw new TypeError('writer must be a function'); R.write = writer; }");
            output.AppendLine("export const manifest = Object.freeze({ assembly: metadata.assembly, profile: metadata.profile, exports: Object.keys(metadata.exports) });");
            output.AppendLine("if (metadata.entry !== null && typeof process !== 'undefined' && process.versions?.node && process.argv[1] && import.meta.url === (await import('node:url')).pathToFileURL(process.argv[1]).href) {\n    try { process.exitCode = main(process.argv.slice(2)); }\n    catch (error) { if (!(error instanceof CliError)) throw error; process.stderr.write(error.message + '\\n'); process.exitCode = 1; }\n}");
        }
        return new(output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal), python ? ".py" : ".mjs", analysis.Methods.Length, count);
    }

    private static string Quote(string value) => JsonSerializer.Serialize(value);
    private static string Bool(bool value, bool python) => python ? value ? "True" : "False" : value ? "true" : "false";
    private static string Number(object value, bool python)
    {
        if (value is long integer) return integer.ToString(CultureInfo.InvariantCulture) + (python ? "" : "n");
        if (value is double d)
        {
            if (double.IsNaN(d)) return python ? "float('nan')" : "NaN";
            if (double.IsPositiveInfinity(d)) return python ? "float('inf')" : "Infinity";
            if (double.IsNegativeInfinity(d)) return python ? "-float('inf')" : "-Infinity";
            if (d == 0 && BitConverter.DoubleToInt64Bits(d) < 0) return "-0.0";
            var text = d.ToString("R", CultureInfo.InvariantCulture);
            return text.IndexOfAny(['.', 'E', 'e']) < 0 ? text + ".0" : text;
        }
        return Convert.ToString(value, CultureInfo.InvariantCulture)!;
    }

    private static void EmitMethod(StringBuilder output, MethodAnalysis analysis, BackendMetadata metadata, AssemblyModel image, bool python)
    {
        var method = analysis.Method;
        var nullValue = python ? "None" : "null";
        var argumentTypes = method.IsStatic ? method.Reference.Parameters : new[] { method.Reference.Type + (image.FindType(method.Reference.Type)?.IsValueType == true ? "&" : "") }.Concat(method.Reference.Parameters).ToArray();
        var args = "[" + string.Join(", ", argumentTypes.Select((type, index) => $"R.coerce(a[{index}], {Quote(type)})")) + "]";
        var locals = "[" + string.Join(", ", method.Locals.Select(type => "R.default(" + Quote(type) + ")")) + "]";
        var clauses = JsonSerializer.Serialize(method.Exceptions, JsonOptions);
        if (python)
        {
            output.AppendLine($"\n# {method.Key}\ndef m_{method.Token}(a):\n    a = {args}\n    s = []\n    l = {locals}\n    pc = 0\n    flow = CliFlow(R, _json.loads({Quote(clauses)}))\n    while True:\n        if pc < 0:\n            raise flow.escaping\n        try:\n            match pc:");
        }
        else
        {
            output.AppendLine($"\n// {method.Key}\nfunction m_{method.Token}(a) {{\n    a = {args};\n    const s = [], l = {locals};\n    let pc = 0, x, y, z;\n    const flow = new CliFlow(R, {clauses});\n    while (true) {{\n        if (pc < 0) throw flow.escaping;\n        try {{\n            switch (pc) {{");
        }
        foreach (var instruction in method.Instructions.Where(i => analysis.StackBefore.ContainsKey(i.Offset)))
        {
            var i = instruction;
            output.AppendLine(python ? $"                case {i.Offset}:  # IL_{i.Offset:x4}: {i.Op}" : $"                case {i.Offset}: // IL_{i.Offset:x4}: {i.Op}");
            void Line(string text) => output.AppendLine("                    " + text + (python ? "" : ";"));
            void Push(string expression) => Line($"s.{(python ? "append" : "push")}({expression})");
            void Pop(string variable) => Line(variable + " = s.pop()");
            void Jump(string expression) { Line("pc = " + expression); Line("continue"); }
            string Kind(int fromEnd) => analysis.StackBefore[i.Offset][^fromEnd];
            string Choice(string condition, string yes, string no) => python ? $"{yes} if {condition} else {no}" : $"{condition} ? {yes} : {no}";
            var terminal = false;
            var op = i.Op;
            if (op == "nop") Line(python ? "pass" : "void 0");
            else if (op is "ldarg" or "ldloc") Push($"R.copy_value({(op == "ldarg" ? "a" : "l")}[{i.Operand}])");
            else if (op is "ldarga" or "ldloca")
            {
                var index = (int)i.Operand!;
                Push($"R.cell_ref({(op == "ldarga" ? "a" : "l")}, {index}, {Quote((op == "ldarga" ? argumentTypes : method.Locals)[index])})");
            }
            else if (op is "starg" or "stloc")
            {
                var index = (int)i.Operand!;
                Line($"{(op == "starg" ? "a" : "l")}[{index}] = R.coerce(s.pop(), {Quote((op == "starg" ? argumentTypes : method.Locals)[index])})");
            }
            else if (op.StartsWith("ldc.", StringComparison.Ordinal)) Push(Number(i.Operand!, python));
            else if (op == "ldnull") Push(nullValue);
            else if (op == "ldstr") Push($"R.string({Quote((string)i.Operand!)}, {Bool(true, python)})");
            else if (op == "dup") Push(python ? "R.copy_value(s[-1])" : "R.copy_value(s[s.length - 1])");
            else if (op == "pop") Line("s.pop()");
            else if (op.StartsWith("conv.", StringComparison.Ordinal)) Push($"R.convert({Quote(op)}, s.pop(), {Quote(Kind(1))})");
            else if (op is "neg" or "not") Push($"R.unary({Quote(op)}, s.pop(), {Quote(Kind(1))})");
            else if (op is "ldftn" or "ldvirtftn")
            {
                var reference = (MethodReference)i.Operand!;
                Push($"R.function_pointer({Quote(metadata.MethodId(reference))}, {(op == "ldvirtftn" ? "s.pop()" : nullValue)}, {Bool(op == "ldvirtftn", python)})");
            }
            else if (op is "call" or "callvirt" or "newobj")
            {
                var reference = (MethodReference)i.Operand!;
                var count = reference.Parameters.Length + (reference.Instance && op != "newobj" ? 1 : 0);
                Line("z = [" + string.Join(", ", Enumerable.Repeat("s.pop()", count)) + "]");
                if (count > 1) Line("z.reverse()");
                var constraint = op == "callvirt" ? method.Instructions.LastOrDefault(p => p.NextOffset == i.Offset && p.Op == "constrained.")?.Operand as string : null;
                var constraintArgument = constraint is null ? "" : ", " + Quote(constraint);
                var expression = op == "newobj" ? $"R.new_object({Quote(metadata.MethodId(reference))}, z)" :
                    $"R.call({Quote(metadata.MethodId(reference))}, z, {Bool(op == "callvirt", python)}{constraintArgument})";
                if (op == "newobj" || reference.ReturnType != "System.Void") Push(expression); else Line(expression);
            }
            else if (op is "ldfld" or "ldsfld" or "ldflda" or "ldsflda")
            {
                var field = (FieldReference)i.Operand!;
                var receiver = op.StartsWith("lds", StringComparison.Ordinal) ? nullValue : "s.pop()";
                Push($"R.{(op.EndsWith('a') ? "field_ref" : "field_get")}({receiver}, {Quote(field.Key)})");
            }
            else if (op is "stfld" or "stsfld")
            {
                Pop("y"); var receiver = nullValue;
                if (op == "stfld") { Pop("x"); receiver = "x"; }
                Line($"R.field_set({receiver}, {Quote(((FieldReference)i.Operand!).Key)}, y)");
            }
            else if (op == "newarr") Push($"R.array({Quote((string)i.Operand!)}, s.pop())");
            else if (op == "ldlen") Push("R.array_length(s.pop())");
            else if (op.StartsWith("ldelem", StringComparison.Ordinal))
            {
                Pop("y"); Pop("x");
                Push($"R.{(op == "ldelema" ? "array_ref" : "array_get")}(x, y, {Quote(CompilerAnalysis.ElementType(i))})");
            }
            else if (op.StartsWith("stelem", StringComparison.Ordinal))
            {
                Pop("z"); Pop("y"); Pop("x"); Line($"R.array_set(x, y, z, {Quote(CompilerAnalysis.ElementType(i))})");
            }
            else if (op.StartsWith("ldind", StringComparison.Ordinal) || op == "ldobj") Push($"R.load_ref(s.pop(), {Quote(CompilerAnalysis.ElementType(i))})");
            else if (op.StartsWith("stind", StringComparison.Ordinal) || op == "stobj")
            { Pop("y"); Pop("x"); Line($"R.store_ref(x, y, {Quote(CompilerAnalysis.ElementType(i))})"); }
            else if (op == "constrained.") Line(python ? "pass" : "void 0");
            else if (op == "cpobj") { Pop("y"); Pop("x"); Line($"R.store_ref(x, R.load_ref(y, {Quote((string)i.Operand!)}), {Quote((string)i.Operand!)})"); }
            else if (op == "initobj") Line($"R.store_ref(s.pop(), R.default({Quote((string)i.Operand!)}), {Quote((string)i.Operand!)})");
            else if (op == "box") Push($"R.box(s.pop(), {Quote((string)i.Operand!)})");
            else if (op is "unbox" or "unbox.any") Push($"R.unbox(s.pop(), {Quote((string)i.Operand!)}, {Bool(op == "unbox", python)})");
            else if (op is "castclass" or "isinst") Push($"R.cast(s.pop(), {Quote((string)i.Operand!)}, {Bool(op == "isinst", python)})");
            else if (op == "ret")
            { Line("return " + (method.Reference.ReturnType == "System.Void" ? nullValue : $"R.coerce(s.pop(), {Quote(method.Reference.ReturnType)})")); terminal = true; }
            else if (op == "br") { Jump(Number(i.Operand!, python)); terminal = true; }
            else if (op is "brtrue" or "brfalse")
            {
                Pop("x"); var condition = op == "brtrue" ? "R.truth(x)" : (python ? "not R.truth(x)" : "!R.truth(x)");
                Jump(Choice(condition, Number(i.Operand!, python), i.NextOffset.ToString(CultureInfo.InvariantCulture))); terminal = true;
            }
            else if (op == "switch")
            {
                var targets = (int[])i.Operand!;
                Pop("x"); Line("z = [" + string.Join(", ", targets) + "]");
                var condition = python ? $"0 <= x < {targets.Length}" : $"x >= 0 && x < {targets.Length}";
                Jump(Choice(condition, "z[x]", i.NextOffset.ToString(CultureInfo.InvariantCulture))); terminal = true;
            }
            else if (op == "leave") { Jump($"flow.leave(pc, {i.Operand}, s)"); terminal = true; }
            else if (op == "endfinally") { Jump("flow.resume(s)"); terminal = true; }
            else if (op == "throw") { Line("R.raise_value(s.pop())"); terminal = true; }
            else if (op == "rethrow") { Line("flow.rethrow(pc)"); terminal = true; }
            else
            {
                Pop("y"); Pop("x");
                var compare = op is "ceq" or "cgt" or "cgt.un" or "clt" or "clt.un" || i.Code.FlowControl == FlowControl.Cond_Branch;
                var expression = $"R.{(compare ? "compare" : "binary")}({Quote(op)}, x, y, {Quote(Kind(2))})";
                if (i.Code.FlowControl == FlowControl.Cond_Branch)
                { Jump(Choice(expression, Number(i.Operand!, python), i.NextOffset.ToString(CultureInfo.InvariantCulture))); terminal = true; }
                else Push(expression);
            }
            if (!terminal) Jump(i.NextOffset.ToString(CultureInfo.InvariantCulture));
        }
        if (python)
            output.AppendLine("                case _:\n                    raise RuntimeError('Invalid generated program counter: ' + str(pc))\n        except CliError as error:\n            pc = flow.handle(error, pc, s)");
        else
            output.AppendLine("                default: throw new Error('Invalid generated program counter: ' + pc);\n            }\n        } catch (error) {\n            if (!(error instanceof CliError)) throw error;\n            pc = flow.handle(error, pc, s);\n        }\n    }\n}");
    }
}
