<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Transpiler.Core/Transpiler.Core.csproj" />
    <EmbeddedResource Include="Runtime/runtime.mjs" LogicalName="Transpiler.Runtime.JavaScript" />
    <EmbeddedResource Include="Runtime/runtime.py" LogicalName="Transpiler.Runtime.Python" />
    <EmbeddedResource Include="Runtime/managed.mjs" LogicalName="Transpiler.Runtime.JavaScript.Managed" />
    <EmbeddedResource Include="Runtime/managed.py" LogicalName="Transpiler.Runtime.Python.Managed" />
    <EmbeddedResource Include="Runtime/services.mjs" LogicalName="Transpiler.Runtime.JavaScript.Services" />
    <EmbeddedResource Include="Runtime/services.py" LogicalName="Transpiler.Runtime.Python.Services" />
    <EmbeddedResource Include="Runtime/values.mjs" LogicalName="Transpiler.Runtime.JavaScript.Values" />
    <EmbeddedResource Include="Runtime/values.py" LogicalName="Transpiler.Runtime.Python.Values" />
    <EmbeddedResource Include="Runtime/numeric.mjs" LogicalName="Transpiler.Runtime.JavaScript.Numeric" />
    <EmbeddedResource Include="Runtime/numeric.py" LogicalName="Transpiler.Runtime.Python.Numeric" />
    <EmbeddedResource Include="Runtime/exceptions.mjs" LogicalName="Transpiler.Runtime.JavaScript.Exceptions" />
    <EmbeddedResource Include="Runtime/exceptions.py" LogicalName="Transpiler.Runtime.Python.Exceptions" />
    <EmbeddedResource Include="Runtime/arrays.mjs" LogicalName="Transpiler.Runtime.JavaScript.Arrays" />
    <EmbeddedResource Include="Runtime/arrays.py" LogicalName="Transpiler.Runtime.Python.Arrays" />
    <EmbeddedResource Include="Runtime/streams.mjs" LogicalName="Transpiler.Runtime.JavaScript.Streams" />
    <EmbeddedResource Include="Runtime/streams.py" LogicalName="Transpiler.Runtime.Python.Streams" />
    <EmbeddedResource Include="Runtime/search.mjs" LogicalName="Transpiler.Runtime.JavaScript.Search" />
    <EmbeddedResource Include="Runtime/search.py" LogicalName="Transpiler.Runtime.Python.Search" />
    <EmbeddedResource Include="Runtime/NOTICE.txt" LogicalName="Transpiler.Runtime.DotNetNotice" />
  </ItemGroup>
</Project>
