<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/Transpiler.Core/Transpiler.Core.csproj" /><ProjectReference Include="../../src/Transpiler.Frontend.Roslyn/Transpiler.Frontend.Roslyn.csproj" /></ItemGroup>
</Project>
